apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv mysql 3306; do echo waiting for mysql; sleep 2; done;"]
      containers:
      - name: api
        image: moshe5434/sql-api:v1
        ports:
        - containerPort: 8000